package com.model;

// Generated Feb 20, 2018 10:13:49 AM by Hibernate Tools 3.4.0.CR1

/**
 * Stud generated by hbm2java
 */
public class Stud implements java.io.Serializable {

	private Integer id;
	private String name;
	private String mobileNo;

	public Stud() {
	}

	public Stud(String name, String mobileNo) {
		this.name = name;
		this.mobileNo = mobileNo;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getMobileNo() {
		return this.mobileNo;
	}

	public void setMobileNo(String mobileNo) {
		this.mobileNo = mobileNo;
	}

}
